################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/no_border_on_floating
source = ~/.config/hypr/conf/monitor.conf


###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$fileManager = thunar
$menu = rofi -show drun


#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

source = ~/.config/hypr/conf/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################


source = ~/.config/hypr/conf/environment.conf

###################
### PERMISSIONS ###
###################



#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/conf/decoration.conf

source = ~/.config/hypr/conf/animation.conf

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

source = ~/.config/hypr/conf/misc.conf


#############
### INPUT ###
#############

source = ~/.config/hypr/conf/keyboard.conf


###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/conf/keybindings.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/conf/windowrules.conf

